import type { GrantProject, GrantStepKey } from '../../types/grant'

export const grantSteps: Array<{ key: GrantStepKey; title: string; route: string; description: string }> = [
  { key: 'input', title: '输入选题信息', route: 'input', description: '基金类型、研究方向、高级条件' },
  { key: 'keywords', title: '选题关键词', route: 'keywords', description: 'AND / OR 与六类关键词池' },
  { key: 'topics', title: '基金选题', route: 'topics', description: '候选题对比和最终选择' },
  { key: 'report', title: '选题报告', route: 'report', description: '立项论证和选题评估' },
  { key: 'proposal', title: '申请书生成', route: 'proposal', description: '分章节生成和导出 Word' },
]

export const grantMockProject: GrantProject = {
  id: 128,
  title: 'PD-1介导的CD8+ T细胞耗竭与黑色素瘤免疫治疗耐药机制',
  status: 'proposal_ready',
  currentStep: 'proposal',
  updatedAt: '2026-06-09 11:52',
  input: {
    fundType: '国自然-青年基金',
    researchAreaPath: ['医学科学部', '肿瘤学', '肿瘤免疫'],
    subject: 'pd1 mediated cd8 t cell exhaustion melanoma immunotherapy resistance',
    diseasePath: ['肿瘤', '黑色素瘤'],
    phenotype: 'T细胞耗竭',
    variableType: '膜受体',
    variableName: 'pd1',
  },
  keywords: {
    must: [{ id: 'must-pd1', text: 'PD-1', source: 'ai', selected: true }],
    should: [
      { id: 'or-melanoma-zh', text: '黑色素瘤', source: 'ai', selected: true, groupKey: 'disease' },
      { id: 'or-exhaustion', text: 'T细胞耗竭', source: 'ai', selected: true, groupKey: 'phenotype' },
      { id: 'or-receptor', text: '膜受体', source: 'ai', selected: true, groupKey: 'target' },
      { id: 'or-pd1', text: 'pd1', source: 'user', selected: true, groupKey: 'target' },
      { id: 'or-melanoma-en', text: 'Melanoma', source: 'ai', selected: true, groupKey: 'disease' },
      { id: 'or-cd8', text: 'CD8+ T cell', source: 'ai', selected: true, groupKey: 'phenotype' },
      { id: 'or-pathway', text: 'PD-1 signaling pathway', source: 'ai', selected: true, groupKey: 'pathway' },
      { id: 'or-ici', text: 'Immune checkpoint inhibitor', source: 'ai', selected: true, groupKey: 'therapy' },
    ],
    groups: [
      {
        key: 'disease',
        label: '关联疾病',
        keywords: [
          { id: 'g1', text: '黑色素瘤', source: 'ai', selected: true },
          { id: 'g2', text: 'Melanoma', source: 'ai', selected: true },
          { id: 'g3', text: '转移性黑色素瘤', source: 'ai', selected: false },
        ],
      },
      {
        key: 'phenotype',
        label: '组织/细胞表型',
        keywords: [
          { id: 'g4', text: 'T细胞耗竭', source: 'ai', selected: true },
          { id: 'g5', text: 'CD8+ T cell', source: 'ai', selected: true },
          { id: 'g6', text: '肿瘤浸润淋巴细胞', source: 'ai', selected: false },
        ],
      },
      {
        key: 'target',
        label: '分子靶点',
        keywords: [
          { id: 'g7', text: 'PD-1', source: 'ai', selected: true },
          { id: 'g8', text: 'PDCD1', source: 'ai', selected: false },
          { id: 'g9', text: 'Tim-3', source: 'ai', selected: false },
        ],
      },
      {
        key: 'pathway',
        label: '信号通路',
        keywords: [
          { id: 'g10', text: 'PD-1 signaling pathway', source: 'ai', selected: true },
          { id: 'g11', text: 'TCR signaling', source: 'ai', selected: false },
          { id: 'g12', text: '线粒体动力学', source: 'ai', selected: false },
        ],
      },
      {
        key: 'therapy',
        label: '治疗方法',
        keywords: [
          { id: 'g13', text: 'Immune checkpoint inhibitor', source: 'ai', selected: true },
          { id: 'g14', text: 'PD-1阻断', source: 'ai', selected: false },
          { id: 'g15', text: '联合免疫治疗', source: 'ai', selected: false },
        ],
      },
      {
        key: 'technique',
        label: '研究技术',
        keywords: [
          { id: 'g16', text: '单细胞测序', source: 'ai', selected: false },
          { id: 'g17', text: '流式细胞术', source: 'ai', selected: false },
          { id: 'g18', text: '空间转录组', source: 'ai', selected: false },
        ],
      },
    ],
  },
  references: [
    {
      id: 'ref-1',
      pmid: '37200001',
      doi: '10.1016/j.cell.2023.immune.001',
      title: 'PD-1 signaling remodels exhausted CD8+ T cells in melanoma microenvironment',
      journal: 'Cell',
      year: 2023,
      evidenceNote: '支持 PD-1 信号与 CD8+ T 细胞耗竭的机制关联。',
      selectedForGeneration: true,
    },
    {
      id: 'ref-2',
      pmid: '36880002',
      doi: '10.1038/s41590-023-immune',
      title: 'Heterogeneity of PD-1hi tumor-infiltrating CD8 T cells predicts checkpoint response',
      journal: 'Nature Immunology',
      year: 2023,
      evidenceNote: '支持 PD-1hi CD8+ T 细胞亚群与免疫治疗疗效相关。',
      selectedForGeneration: true,
    },
    {
      id: 'ref-3',
      pmid: '35510003',
      doi: '10.1158/0008-5472.can-22-immune',
      title: 'T cell exhaustion and resistance to immune checkpoint blockade in melanoma',
      journal: 'Cancer Research',
      year: 2022,
      evidenceNote: '支持黑色素瘤免疫治疗耐药与 T 细胞耗竭之间的关系。',
      selectedForGeneration: true,
    },
  ],
  topics: [
    {
      id: 'topic-1',
      title: 'PD-1介导的CD8+ T细胞耗竭与黑色素瘤免疫治疗耐药机制',
      description: '聚焦PD-1信号通路如何驱动黑色素瘤微环境中CD8+ T细胞功能耗竭，探究其对免疫检查点抑制剂疗效的影响及潜在逆转策略。',
      innovation: '把免疫检查点信号、T 细胞耗竭状态和治疗耐药放入同一机制链路。',
      feasibility: '可通过流式、单细胞数据和体外功能实验组合验证。',
      fundFit: '问题聚焦、机制清晰，适合青年基金。',
      risk: '需避免题目过大，聚焦 PD-1 下游关键节点。',
      score: { innovation: 88, feasibility: 84, fundFit: 91, evidence: 86 },
      referenceIds: ['ref-1', 'ref-2', 'ref-3'],
      selected: true,
    },
    {
      id: 'topic-2',
      title: '黑色素瘤中PD-1与Tim-3共表达调控CD8+ T细胞耗竭的分子机制',
      description: '强调共抑制受体协同调控，适合走免疫逃逸和细胞状态转换方向。',
      innovation: '从双检查点共表达切入，具备联合治疗延展空间。',
      feasibility: '需要双阳性细胞群分选和功能验证。',
      fundFit: '青年基金可行，但变量较多。',
      risk: 'Tim-3 可能扩大研究范围。',
      score: { innovation: 83, feasibility: 76, fundFit: 80, evidence: 78 },
      referenceIds: ['ref-2'],
      selected: false,
    },
    {
      id: 'topic-3',
      title: 'Rab37介导的PD-1膜定位在黑色素瘤T细胞耗竭中的作用',
      description: '切入膜定位和小 GTP 酶调控，创新性较强但实验路径要求更高。',
      innovation: '从膜定位机制解释 PD-1 信号维持，角度更细。',
      feasibility: '需要膜蛋白定位、共聚焦和干预实验。',
      fundFit: '创新性高，技术风险也高。',
      risk: '预实验基础不足时申报风险偏高。',
      score: { innovation: 91, feasibility: 68, fundFit: 73, evidence: 62 },
      referenceIds: ['ref-1'],
      selected: false,
    },
    {
      id: 'topic-4',
      title: 'PD-1信号通路通过Drp1调控线粒体动力学影响CD8+ T细胞耗竭',
      description: '连接免疫检查点和代谢/线粒体动力学，可作为机制深化备选。',
      innovation: '把耗竭表型与线粒体动力学连接。',
      feasibility: '可通过 Drp1 干预和代谢功能检测验证。',
      fundFit: '适合机制研究，但需要明确关键假说。',
      risk: '可能偏离 PD-1 主线。',
      score: { innovation: 86, feasibility: 72, fundFit: 78, evidence: 70 },
      referenceIds: ['ref-1', 'ref-3'],
      selected: false,
    },
    {
      id: 'topic-5',
      title: 'PD-1hi CD8+ T细胞亚群在黑色素瘤中的异质性及其临床意义',
      description: '聚焦 PD-1 高表达细胞群异质性和临床关联。',
      innovation: '偏队列和分型，临床转化意义更突出。',
      feasibility: '依赖样本队列和单细胞数据。',
      fundFit: '适配度中等，更像面上或临床转化题。',
      risk: '青年基金可能显得范围较大。',
      score: { innovation: 78, feasibility: 74, fundFit: 70, evidence: 82 },
      referenceIds: ['ref-2'],
      selected: false,
    },
    {
      id: 'topic-6',
      title: 'PD-1阻断后肿瘤引流淋巴结中CD8+ T细胞功能重塑的机制',
      description: '把研究范围前移到肿瘤引流淋巴结，关注免疫治疗后 T 细胞功能重塑。',
      innovation: '从治疗后免疫生态重塑解释疗效差异。',
      feasibility: '需要治疗前后样本或动物模型支持。',
      fundFit: '机制路径清楚，但样本获取要求较高。',
      risk: '临床样本时序可能成为限制。',
      score: { innovation: 82, feasibility: 70, fundFit: 76, evidence: 74 },
      referenceIds: ['ref-2', 'ref-3'],
      selected: false,
    },
    {
      id: 'topic-7',
      title: 'PD-1与LAG-3协同调控CD8+ T细胞耗竭在黑色素瘤中的免疫逃逸机制',
      description: '围绕双检查点协同调控和免疫逃逸展开，适合延伸联合免疫治疗方向。',
      innovation: '兼顾机制研究和联合治疗转化价值。',
      feasibility: '需要控制变量，避免检查点过多导致研究发散。',
      fundFit: '适合有联合治疗基础的申报团队。',
      risk: 'LAG-3 会扩大课题边界。',
      score: { innovation: 84, feasibility: 71, fundFit: 78, evidence: 76 },
      referenceIds: ['ref-3'],
      selected: false,
    },
    {
      id: 'topic-8',
      title: 'STAT5调控PD-1转录活性影响CD8+ T细胞耗竭敏感性的机制',
      description: '从转录调控层面解释 PD-1 表达维持和耗竭易感性。',
      innovation: '把转录因子调控和免疫耗竭状态连接。',
      feasibility: '可通过转录因子干预、报告基因和 ChIP 验证。',
      fundFit: '机制链条较完整，适合基础研究。',
      risk: '需要证明 STAT5 与 PD-1 调控的直接性。',
      score: { innovation: 87, feasibility: 73, fundFit: 80, evidence: 66 },
      referenceIds: ['ref-1'],
      selected: false,
    },
    {
      id: 'topic-9',
      title: 'PD-1信号通路在肿瘤抗原特异性CD8+ T细胞功能衰竭中的作用',
      description: '聚焦肿瘤抗原特异性 T 细胞，更强调抗原识别和效应功能下降。',
      innovation: '从抗原特异性细胞群解释耗竭和治疗反应。',
      feasibility: '需要抗原特异性细胞检测或四聚体实验。',
      fundFit: '有明确实验体系时适配度较高。',
      risk: '技术门槛较高，需预实验支撑。',
      score: { innovation: 80, feasibility: 69, fundFit: 72, evidence: 68 },
      referenceIds: ['ref-1', 'ref-3'],
      selected: false,
    },
    {
      id: 'topic-10',
      title: 'PD-1介导的CD8+ T细胞耗竭影响免疫检查点抑制剂安全性的机制',
      description: '从疗效之外关注安全性和免疫相关不良反应，形成差异化选题。',
      innovation: '将耗竭状态与免疫治疗安全性关联。',
      feasibility: '需要安全性数据或炎症因子谱支持。',
      fundFit: '方向新，但与青年基金基础机制定位需进一步收敛。',
      risk: '安全性终点可能偏临床观察。',
      score: { innovation: 76, feasibility: 64, fundFit: 68, evidence: 60 },
      referenceIds: ['ref-3'],
      selected: false,
    },
  ],
  reportSections: [
    {
      key: 'purpose',
      title: '研究目的、意义',
      markdown: '本项目拟阐明 PD-1 信号介导 CD8+ T 细胞耗竭并导致黑色素瘤免疫治疗耐药的关键机制，为提高免疫检查点抑制剂疗效提供理论依据。',
    },
    {
      key: 'content',
      title: '研究内容及实现方案',
      markdown: '围绕 PD-1 高表达 CD8+ T 细胞功能状态、下游信号变化和治疗反应差异三个层面展开，结合临床样本、细胞功能实验和机制干预验证。',
    },
    {
      key: 'hypothesis',
      title: '科学问题和科学假说',
      markdown: '科学假说：PD-1 持续激活通过重塑 CD8+ T 细胞效应功能和代谢状态，推动耗竭表型稳定化，从而降低黑色素瘤对免疫检查点抑制剂的响应。',
    },
    {
      key: 'evaluation',
      title: '选题评估',
      markdown: '该题目问题聚焦、机制路径清晰、文献基础较充分，适合青年基金。但需要在申请书中控制研究范围，聚焦 1-2 个关键机制节点。',
    },
  ],
  proposalSections: [
    {
      key: 'abstract',
      title: '中文摘要、关键词',
      status: 'ready',
      wordCount: 420,
      markdown: '黑色素瘤免疫治疗耐药是限制免疫检查点抑制剂疗效的关键问题。本项目拟围绕 PD-1 介导的 CD8+ T 细胞耗竭机制展开研究，解析其在耐药形成中的作用。',
    },
    {
      key: 'attribute',
      title: '科学问题属性选择理由',
      status: 'ready',
      wordCount: 360,
      markdown: '本项目聚焦免疫治疗耐药中的基础机制问题，属于从疾病现象凝练关键科学问题并开展机制研究的类型。',
    },
    {
      key: 'basis',
      title: '项目立项依据',
      status: 'ready',
      wordCount: 1680,
      markdown: '免疫检查点抑制剂显著改善了黑色素瘤治疗格局，但仍有相当比例患者应答不足或发生继发耐药。CD8+ T 细胞耗竭被认为是影响抗肿瘤免疫效应的重要因素。',
    },
    {
      key: 'content',
      title: '项目的研究内容',
      status: 'ready',
      wordCount: 980,
      markdown: '研究内容一：明确黑色素瘤中 PD-1 高表达 CD8+ T 细胞的耗竭特征。研究内容二：解析 PD-1 信号维持耗竭状态的关键分子机制。',
    },
    {
      key: 'route',
      title: '技术路线图',
      status: 'needs_review',
      wordCount: 240,
      markdown: 'Mermaid 图示待校验。若渲染失败，应展示源码并允许重新生成图示。',
    },
  ],
}
